### ISSUE TITLE
Find markdown URL generator code

### ISSUE THREAD

**Issue by apaskulin** [apaskulin/contensifier#1]
@arthurbenemann Is it this? https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb

**Comment by arthurbenemann** [comment]
Yeah, it looks like it is. These are the line that needs to be replaced:
- https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L40
- https://github.com/apaskulin/contensifier/blob/master/contensifier.py#L21

And this one is already there:
- https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L41
- https://github.com/apaskulin/contensifier/blob/master/contensifier.py#L31

**Comment by arthurbenemann** [comment]
fixed by #2
